# Generated by Django 6.0 on 2025-12-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ContentType',
            new_name='content_type',
        ),
    ]
