# Generated by Django 6.0 on 2025-12-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_created_at_comment_modified_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='puplished_at',
            new_name='published_at',
        ),
    ]
